### ISSUE TITLE
German translation

### ISSUE THREAD

**Issue by dab339** [jawhien/extendedTotalCmd#13]
Hi,

i promis you a german translation of your Addon.
Here comes it.

I send you the Source and a complete Addon with german files included.
Regards
Ilja
[Total Commander-Addon-DE.zip](https://github.com/user-attachments/files/16596917/Total.Commander-Addon-DE.zip)

**Comment by jawhien** [comment]
@dab339
Thank you. I'll add it.
Please note that when add-on updating, the localization also needs to be updated.
